create table public.account_table (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  email text null,
  password text null,
  role text null,
  security_question text null,
  security_answer text null,
  constraint account_table_pkey primary key (id)
) TABLESPACE pg_default;

create table public.intro_advertisements (
  slot_id bigint generated by default as identity not null,
  image_url character varying null,
  image_name text null,
  constraint intro_advertisements_pkey primary key (slot_id)
) TABLESPACE pg_default;

create table public.payment_table (
  pymnt_id bigint generated by default as identity not null,
  fk_trans_id bigint not null,
  pymnt_ref_id text null,
  order_number bigint null,
  pymnt_mthod text null,
  pymnt_status text null,
  pymnt_amount numeric null,
  pymnt_change numeric null,
  pymnt_date date null,
  pymnt_time time without time zone null,
  constraint payment_table_pkey primary key (pymnt_id)
) TABLESPACE pg_default;

create table public.product_details (
  product_id bigint generated by default as identity not null,
  prdct_name text null,
  prdct_dscrpt text null,
  prdct_price numeric null,
  prdct_categ text null,
  is_available boolean null,
  prdct_imgurl character varying null,
  constraint product_details_pkey primary key (product_id)
) TABLESPACE pg_default;

create table public.trans_items_table (
  trans_item_id bigint generated by default as identity not null,
  fk_trans_id bigint not null,
  fk_prod_id character varying null,
  prdct_name character varying null,
  quantity integer null,
  unit_price numeric null,
  item_subtotal numeric null,
  order_notes character varying null,
  constraint trans_items_table_pkey primary key (trans_item_id)
) TABLESPACE pg_default;

create table public.trans_table (
  id smallint generated by default as identity not null,
  trans_id bigint generated by default as identity not null,
  ref_number character varying null,
  order_number numeric null,
  order_type text null,
  trans_date date null,
  trans_time time without time zone null,
  order_status text null,
  pymnt_status text null,
  pymnt_method text null,
  total_amntdue numeric null,
  amount_paid numeric null,
  user_id text null,
  constraint trans_table_pkey primary key (id, trans_id)
) TABLESPACE pg_default;